### ISSUE TITLE
Issues using function rfb

### ISSUE THREAD

**Issue by pazsamp** [shfischer/cat3advice#3]
Hi Simon, 

I updated the library cat3advice to use for running the advice for pollack in 89a and the rfb function breaks when I use an "A" calculated as the average of the last three years catches (avg_years=3, in A function). I checked the object A and A@avg_years = c(2021, 2022, 2023),  if I sustitute by c(3)  si running.

Thank you very much for the library and your help,

**Comment by shfischer** [comment]
Hi Paz,

Thanks for reporting this bug. I added a bug fix with the latest commit https://github.com/shfischer/cat3advice/commit/eebd32503828a301c21f922baeccadc007dc822e and it should work now:

`A(data.frame(year = 2000:2009, catch = 1:10), avg_years = 2005:2007, basis = "average catch", units = "tonnes")`
